spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEnconding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        # Spring Boot 的 META-INF/spring-configuration-metadata.json 配置文件中默认是关闭 Spring 的 hiddenmethod 过滤器的。
        # 这时候需要通Springboot配置文件application.yml/properties 中将 hiddenmethod 过滤器设置为启用即可。 可以配置delete put等请求
  messages:
    basename: i18n.messages # 国际化的配置文件路径
  redis:
    host: 127.0.0.1
    port: 6379
    password:
mybatis:
  type-aliases-package: com.hyb.pojo
  mapper-locations: classpath:com/hyb/mapper/*.xml

pagehelper:
  helper-dialect: mysql  #指定数据库，不指定的话会默认自动检测数据库类型
  reasonable: true  #是否启用分页合理化。如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；不启用的，以上两种情况都会返回空数据
  support-methods-arguments: true #默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  params: countSql #用于从对象中根据属性名取值
logging:
  level:
    com.hyb.mapper: debug  # 控制台打印sql

comment.avatar: https://s2.loli.net/2022/03/06/9L1fvzXHtyGuU7E.jpg